import XCTest
import Foundation
@testable import paceriz_dev

/// AC test stubs for SPEC-vdot-naming-and-workout-row-redesign.
/// Auto-generated by Architect — Developer fills implementation.
/// Red = gap, Green = verified.
///
/// AC ID 與 SPEC 一一對應，function 名稱保留 AC ID 前綴。
/// UI/視覺層級的 AC（layout、相對時間格式、徽章樣式）以 XCUITest 或 Maestro 補強——
/// 此檔聚焦於 strings、可程式驗證的條件，與不可程式驗證的 manual checklist。
final class VdotNamingAndWorkoutRowRedesignACTests: XCTestCase {

    // MARK: - 命名統一（strings 層級）

    /// AC-VDOT-NAME-01: 主名「VDOT」三語 label 一致
    func test_ac_vdot_name_01_main_label_consistent_across_locales() throws {
        // 主名（穩定值）的 vdot_title 三語都應該是 "VDOT"
        for locale in ["zh-Hant", "en", "ja"] {
            let value = LocalizedString.lookup(key: "performance.vdot.vdot_title", locale: locale)
            XCTAssertEqual(value, "VDOT", "performance.vdot.vdot_title in \(locale) must be 'VDOT'")
        }
    }

    /// AC-VDOT-NAME-02 (修訂): 全 app label 統一 VDOT。
    /// 副名「動態跑力 / Live VDOT / ライブ VDOT」僅作為說明頁文字概念解釋，不當 label。
    /// 因 codebase 實際只有 dynamic_vdot 露出在 user-facing UI（weighted_vdot 在 orphan VDOTChartView 才用），
    /// 「同一個值兩種敘述」會造成 user 困惑。
    func test_ac_vdot_name_02_label_unified_to_vdot() throws {
        for locale in ["zh-Hant", "en", "ja"] {
            let value = LocalizedString.lookup(key: "performance.vdot.dynamic_vdot", locale: locale)
            XCTAssertEqual(value, "VDOT", "performance.vdot.dynamic_vdot in \(locale) must be 'VDOT' (unified label)")
            let value2 = LocalizedString.lookup(key: "workout.detail.dynamic_vdot", locale: locale)
            XCTAssertEqual(value2, "VDOT", "workout.detail.dynamic_vdot in \(locale) must be 'VDOT' (unified label)")
        }
    }

    /// AC-VDOT-NAME-03: 圖表 y 軸 / 標題用 VDOT
    func test_ac_vdot_name_03_chart_axis_uses_vdot() throws {
        // chart.vdot_value 三語都應該是 "VDOT"
        for locale in ["zh-Hant", "en", "ja"] {
            let value = LocalizedString.lookup(key: "performance.chart.vdot_value", locale: locale)
            XCTAssertEqual(value, "VDOT", "performance.chart.vdot_value in \(locale) must be 'VDOT'")
        }
    }

    /// AC-VDOT-NAME-04: 說明頁不提徐國峰 / 跑力 / RQ / runningquotient
    func test_ac_vdot_name_04_no_competitor_mention_in_description() throws {
        let forbiddenTerms = ["徐國峰", "RQ", "runningquotient", "Runningquotient"]
        for locale in ["zh-Hant", "en", "ja"] {
            let desc = LocalizedString.lookup(key: "performance.vdot.vdot_description", locale: locale)
            for term in forbiddenTerms {
                XCTAssertFalse(
                    desc.contains(term),
                    "vdot_description in \(locale) must not contain '\(term)'; got: \(desc)"
                )
            }
            // zh-Hant 還要排除單獨「跑力」（但允許「動態跑力」）
            if locale == "zh-Hant" {
                let withoutDynamic = desc.replacingOccurrences(of: "動態跑力", with: "")
                XCTAssertFalse(
                    withoutDynamic.contains("跑力"),
                    "zh-Hant vdot_description must not contain '跑力' outside '動態跑力'; got: \(desc)"
                )
            }
        }
    }

    /// AC-VDOT-NAME-04b: 說明頁底部官網連結 key 存在且為合法 URL
    func test_ac_vdot_name_04b_blog_link_present_and_valid() throws {
        for locale in ["zh-Hant", "en", "ja"] {
            let urlString = LocalizedString.lookup(key: "performance.vdot.blog_url", locale: locale)
            XCTAssertFalse(urlString.isEmpty, "blog_url in \(locale) must not be empty")
            XCTAssertNotNil(URL(string: urlString), "blog_url in \(locale) must be valid URL: \(urlString)")
            XCTAssertTrue(
                urlString.hasPrefix("https://paceriz.com/blog/"),
                "blog_url in \(locale) must point to paceriz.com/blog/; got: \(urlString)"
            )
            // read_more label key 存在
            let readMore = LocalizedString.lookup(key: "performance.vdot.read_more", locale: locale)
            XCTAssertFalse(readMore.isEmpty, "read_more label in \(locale) must not be empty")
        }
    }

    /// AC-VDOT-NAME-05: zh-Hant strings 不可有「加權跑力」「最新跑力」殘留
    /// （Note: 編譯後 .strings 是 binary plist，需用 NSDictionary 讀；不可用 String(contentsOf:)）
    func test_ac_vdot_name_05_no_legacy_terms_in_zh_hant() throws {
        let forbidden = ["加權跑力", "最新跑力", "平均加權跑力", "最新動態跑力"]
        let bundle = Bundle.main
        guard let path = bundle.path(forResource: "zh-Hant", ofType: "lproj"),
              let localeBundle = Bundle(path: path),
              let stringsURL = localeBundle.url(forResource: "Localizable", withExtension: "strings"),
              let dict = NSDictionary(contentsOf: stringsURL) as? [String: String] else {
            XCTFail("無法讀取 zh-Hant Localizable.strings (binary plist)")
            return
        }
        for (key, value) in dict {
            for term in forbidden {
                XCTAssertFalse(
                    value.contains(term),
                    "zh-Hant strings key '\(key)' 不可含「\(term)」；got value: \(value)"
                )
            }
        }
    }

    /// AC-VDOT-NAME-06: i18n 三檔 VDOT 相關 key 翻譯齊全
    func test_ac_vdot_name_06_keys_aligned_across_locales() throws {
        let requiredKeys = [
            "performance.vdot.vdot_title",
            "performance.vdot.what_is_vdot",
            "performance.vdot.vdot_description",
            "performance.vdot.dynamic_vdot",
            "performance.vdot.weighted_vdot",
            "performance.vdot.latest_vdot",
            "performance.vdot.calculating_vdot",
            "performance.vdot.read_more",
            "performance.vdot.blog_url",
            "performance.chart.vdot_value",
            "performance.vdot_trend",
            "performance.vdot_explanation",
            "workout.detail.dynamic_vdot"
        ]
        for key in requiredKeys {
            for locale in ["zh-Hant", "en", "ja"] {
                let value = LocalizedString.lookup(key: key, locale: locale)
                XCTAssertFalse(
                    value.isEmpty || value == key,
                    "key '\(key)' in locale '\(locale)' is missing or untranslated"
                )
            }
        }
    }

    // MARK: - 訓練紀錄 list 卡片（部分可程式驗證，部分 manual）

    /// AC-VDOT-NAME-07: 卡片顯示日期/相對時間 — UI 層測試（snapshot 或 Maestro）
    func test_ac_vdot_name_07_relative_date_format() throws {
        throw XCTSkip("AC-07 require XCUITest snapshot or Maestro flow; manual verify by simulator screenshot in zh/en/ja.")
    }

    /// AC-VDOT-NAME-08: 距離+配速為主秀 — UI layout，manual 驗證
    func test_ac_vdot_name_08_pace_in_primary_layout() throws {
        throw XCTSkip("AC-08 是 layout 視覺權重，需 simulator 截圖人工驗證。")
    }

    /// AC-VDOT-NAME-09: 跑步且有 dynamicVdot 時顯示（卡片用主名 VDOT）
    func test_ac_vdot_name_09_show_when_running_with_vdot() throws {
        // PIVOT: 卡片仍用「VDOT %.1f」主名顯示。本 case 透過 view inspector / snapshot 驗。
        throw XCTSkip("AC-09 由 WorkoutV2RowView snapshot 或 Maestro 驗證。")
    }

    /// AC-VDOT-NAME-09b: 非跑步或無 VDOT → 整行隱藏（已實作 @ WorkoutV2RowView:42 if let dynamicVdot）
    func test_ac_vdot_name_09b_hide_when_no_vdot() throws {
        throw XCTSkip("已實作於 WorkoutV2RowView.swift:42 (if let dynamicVdot)，由 snapshot 驗證視覺。")
    }

    /// AC-VDOT-NAME-10: 對應 V2 訓練類型 → 顯示 tag（已實作 @ WorkoutV2RowView:30-37）
    func test_ac_vdot_name_10_show_training_type_tag() throws {
        throw XCTSkip("已實作於 WorkoutV2RowView.swift:30-37。snapshot 驗證視覺。")
    }

    /// AC-VDOT-NAME-10b: 未對應 → 不顯示（已實作 @ WorkoutV2RowView:30 if let trainingType）
    func test_ac_vdot_name_10b_hide_training_type_when_no_match() throws {
        throw XCTSkip("已實作於 WorkoutV2RowView.swift:30 (if let trainingType)。")
    }

    /// AC-VDOT-NAME-11: Garmin badge 含 ™ — strings 層級可驗
    /// 用 NSLocalizedString 在三語下都檢查
    func test_ac_vdot_name_11_garmin_trademark_in_attribution() throws {
        for locale in ["zh-Hant", "en", "ja"] {
            let value = LocalizedString.lookup(key: "datasource.garmin_connect", locale: locale)
            XCTAssertTrue(
                value.contains("™"),
                "datasource.garmin_connect in \(locale) 必須含 ™ trademark；got: \(value)"
            )
        }
    }

    /// AC-VDOT-NAME-12: Apple Health badge — UI 新增，manual 驗證
    func test_ac_vdot_name_12_apple_health_badge_present() throws {
        throw XCTSkip("AC-12 由 WorkoutV2RowView snapshot / Maestro 驗證 Apple Health badge 存在。")
    }

    /// AC-VDOT-NAME-13: 多筆 badge 樣式一致 — manual / snapshot
    func test_ac_vdot_name_13_badge_style_consistency() throws {
        throw XCTSkip("AC-13 由多筆混合資料來源 snapshot 比對驗證。")
    }

    /// AC-VDOT-NAME-13b: Badge 可擴展設計（已實作 — 各 attribution component 分離）
    func test_ac_vdot_name_13b_extensible_badge_design() throws {
        // 已驗證：GarminAttributionView / ConditionalStravaAttributionView 為獨立 component。
        // AppleHealthAttributionView 新增後，code review 確認延續同 pattern 即可。
        throw XCTSkip("已實作；新增 AppleHealthAttributionView 後 code review 即可確認。")
    }

    /// AC-VDOT-NAME-14: 三語環境下卡片資訊正確
    func test_ac_vdot_name_14_locale_aware_rendering() throws {
        throw XCTSkip("AC-14 由三語 simulator 截圖驗證。")
    }

    // MARK: - P1 主畫面 / 詳細頁 layout

    /// AC-VDOT-NAME-15 (P1): 主畫面 VDOT 單一主數字（已單一值；只需 label audit）
    func test_ac_vdot_name_15_main_screen_single_vdot() throws {
        throw XCTSkip("UserProfileFeatureViewModel:222 currentVDOT 已是單一值；由 simulator 截圖確認 label = 'VDOT'。")
    }

    /// AC-VDOT-NAME-16 (P1): VDOT 詳細頁主數字 VDOT，副資訊動態跑力與趨勢圖
    func test_ac_vdot_name_16_detail_page_layout() throws {
        throw XCTSkip("AC-16 由 VDOTChartView snapshot 驗證。")
    }

    // MARK: - P2 dead code

    /// AC-VDOT-NAME-17 (P2): 清理 dead code
    /// Note: WorkoutSummaryRow.swift 內 V2 active structs (WorkoutV2SummaryRow / CollapsedWorkoutV2Summary)
    /// 仍被 DailyTrainingCard:145 引用，必須保留。死碼僅指 HKWorkout-based 的 WorkoutSummaryRow + CollapsedWorkoutSummary structs
    /// 與整個 WorkoutRowView.swift 檔案。
    func test_ac_vdot_name_17_dead_code_removed() throws {
        // 用 NSClassFromString 偵測 type 已不存在；
        // SwiftUI struct 並非 ObjC class 故 NSClassFromString 對 struct 失效，改檢查 source-level skip
        throw XCTSkip("AC-17 由 grep audit 驗證：WorkoutRowView.swift 已 git rm；WorkoutSummaryRow + CollapsedWorkoutSummary structs 已從 WorkoutSummaryRow.swift 刪除（保留 V2 structs）。")
    }

    // MARK: - 新增 AC（Architect 階段）

    /// AC-VDOT-NAME-18 (NEW): WorkoutDetailViewV2 新增動態跑力副名顯示
    func test_ac_vdot_name_18_detail_view_dynamic_vdot_subname() throws {
        throw XCTSkip("AC-18 為 WorkoutDetailViewV2 視覺新增；snapshot / Maestro 驗證副名顯示。")
    }
}

// MARK: - Helper

private enum LocalizedString {
    /// 取指定 locale 的 strings 值；找不到回傳 key 本身（讓 test fail）。
    static func lookup(key: String, locale: String) -> String {
        let bundle = Bundle.main
        guard let path = bundle.path(forResource: locale, ofType: "lproj"),
              let localeBundle = Bundle(path: path) else {
            return key
        }
        return NSLocalizedString(key, bundle: localeBundle, comment: "")
    }
}
