import Combine
import XCTest
@testable import paceriz_dev

/// AC test stubs for SPEC-readiness-v2-conditional-display.
/// Generated by Architect — Developer fills implementation.
/// Red = gap, Green = verified.
final class ReadinessConditionalDisplayACTests: XCTestCase {

    // MARK: - AC-RDNS-01: race_run → 5 維齊全

    /// AC-RDNS-01: Given plan_type = "race_run",
    /// When readiness data loaded,
    /// Then effectivePlanType = .raceRun, all should* flags = true.
    func test_ac_rdns_01_race_run_shows_all() throws {
        let planType = ReadinessPlanType(from: "race_run")

        XCTAssertEqual(planType, .raceRun)
        XCTAssertTrue(planType.shouldShowRadar, "race_run should show radar")
        XCTAssertTrue(planType.shouldShowOverallScore, "race_run should show overall score")
        XCTAssertTrue(planType.shouldShowEstimatedRaceTime, "race_run should show estimated race time")
        XCTAssertTrue(planType.shouldShowStatusText, "race_run should show status text")
    }

    // MARK: - AC-RDNS-02: beginner → 只 speed + training_load

    /// AC-RDNS-02: Given plan_type = "beginner",
    /// When readiness data loaded,
    /// Then effectivePlanType = .beginner;
    ///   shouldShowRadar = false, shouldShowOverallScore = false,
    ///   shouldShowEstimatedRaceTime = false, shouldShowStatusText = false.
    func test_ac_rdns_02_beginner_shows_two_cards() throws {
        let planType = ReadinessPlanType(from: "beginner")

        XCTAssertEqual(planType, .beginner)
        XCTAssertFalse(planType.shouldShowRadar, "beginner should not show radar")
        XCTAssertFalse(planType.shouldShowOverallScore, "beginner should not show overall score")
        XCTAssertFalse(planType.shouldShowEstimatedRaceTime, "beginner should not show estimated race time")
        XCTAssertFalse(planType.shouldShowStatusText, "beginner should not show status text")
    }

    // MARK: - AC-RDNS-03: maintenance → 同 beginner

    /// AC-RDNS-03: Given plan_type = "maintenance",
    /// When readiness data loaded,
    /// Then effectivePlanType = .maintenance; same flags as AC-RDNS-02.
    func test_ac_rdns_03_maintenance_shows_two_cards() throws {
        let planType = ReadinessPlanType(from: "maintenance")

        XCTAssertEqual(planType, .maintenance)
        XCTAssertFalse(planType.shouldShowRadar, "maintenance should not show radar")
        XCTAssertFalse(planType.shouldShowOverallScore, "maintenance should not show overall score")
        XCTAssertFalse(planType.shouldShowEstimatedRaceTime, "maintenance should not show estimated race time")
        XCTAssertFalse(planType.shouldShowStatusText, "maintenance should not show status text")
    }

    /// AC-RDNS-03 companion: non-race readiness UI copy must resolve in all supported languages.
    func test_ac_rdns_03_non_race_copy_is_localized_in_supported_languages() throws {
        let appBundle = Bundle(for: TrainingReadinessViewModel.self)
        let locales = ["en", "ja", "zh-Hant"]
        let keys = [
            "training_readiness.non_race_training_mode",
            "training_readiness.race_only_metrics_footnote",
            "training_readiness.race_only_note_title",
            "training_readiness.race_only_note_body"
        ]

        for locale in locales {
            guard let path = appBundle.path(forResource: locale, ofType: "lproj"),
                  let localeBundle = Bundle(path: path) else {
                XCTFail("Missing \(locale).lproj bundle")
                continue
            }

            for key in keys {
                let value = NSLocalizedString(key, bundle: localeBundle, comment: "")
                XCTAssertFalse(value.isEmpty, "\(key) must not be empty in \(locale)")
                XCTAssertNotEqual(value, key, "\(key) must resolve in \(locale)")
            }
        }
    }

    // MARK: - AC-RDNS-04: V1 fallback → PlanOverviewV2.targetType

    /// AC-RDNS-04: Given readiness doc has no plan_type (planType == nil),
    /// When PlanOverviewV2.targetType = "beginner",
    /// Then effectivePlanType = .beginner (fallback succeeded).
    @MainActor
    func test_ac_rdns_04_fallback_to_plan_overview() throws {
        let vm = TrainingReadinessViewModel()

        // readinessData has no planType (V1 doc — planType is nil)
        vm.readinessData = makeReadinessResponse(planType: nil)

        // Inject planOverviewProvider returning targetType = "beginner"
        vm.planOverviewProvider = { makePlanOverview(targetType: "beginner") }

        XCTAssertEqual(vm.effectivePlanType, .beginner, "Should fall back to PlanOverviewV2.targetType")
    }

    /// AC-RDNS-04 (both nil): Given readiness planType == nil AND planOverview == nil,
    /// When effectivePlanType evaluated,
    /// Then returns .unknown → defaults to race_run display (show all).
    @MainActor
    func test_ac_rdns_04_both_nil_defaults_to_show_all() throws {
        let vm = TrainingReadinessViewModel()

        vm.readinessData = makeReadinessResponse(planType: nil)
        vm.planOverviewProvider = { nil }

        XCTAssertEqual(vm.effectivePlanType, .unknown, "Should return .unknown when both sources are nil")
        XCTAssertTrue(vm.effectivePlanType.shouldShowRadar, ".unknown defaults to show all (race_run conservative)")
        XCTAssertTrue(vm.effectivePlanType.shouldShowOverallScore)
        XCTAssertTrue(vm.effectivePlanType.shouldShowEstimatedRaceTime)
        XCTAssertTrue(vm.effectivePlanType.shouldShowStatusText)
    }

    // MARK: - AC-RDNS-05: plan switch → readiness refresh

    /// AC-RDNS-05: Given TrainingReadinessManager has subscribed to overviewDidUpdate,
    /// When overviewDidUpdate fires with new PlanOverviewV2,
    /// Then forceRefresh() is called on the manager (cache invalidated + re-fetch).
    @MainActor
    func test_ac_rdns_05_plan_switch_triggers_refresh() throws {
        let mockRepo = OverviewPublishingMockRepository()
        let manager = TrainingReadinessManagerTestable(overviewRepository: mockRepo)

        // Fire overviewDidUpdate
        mockRepo.fireOverviewUpdate(makePlanOverview(targetType: "beginner"))

        // Allow the sink's Task to execute
        let expectation = XCTestExpectation(description: "forceRefresh called")
        DispatchQueue.main.asyncAfter(deadline: .now() + 0.1) {
            if manager.forceRefreshCallCount > 0 {
                expectation.fulfill()
            }
        }
        wait(for: [expectation], timeout: 1.0)

        XCTAssertGreaterThan(manager.forceRefreshCallCount, 0, "forceRefresh should be called after overviewDidUpdate fires")
    }
}

// MARK: - Test Helpers

private func makeReadinessResponse(planType: String?) -> TrainingReadinessResponse {
    TrainingReadinessResponse(
        date: "2026-04-28",
        overallScore: 75,
        overallStatusText: nil,
        lastUpdatedTime: nil,
        metrics: nil,
        dataSource: nil,
        lastUpdated: nil,
        planType: planType
    )
}

private func makePlanOverview(targetType: String) -> PlanOverviewV2 {
    PlanOverviewV2(
        id: "test-id",
        targetId: nil,
        targetType: targetType,
        targetDescription: nil,
        methodologyId: nil,
        totalWeeks: 12,
        startFromStage: nil,
        raceDate: nil,
        distanceKm: nil,
        distanceKmDisplay: nil,
        distanceUnit: nil,
        targetPace: nil,
        targetTime: nil,
        isMainRace: nil,
        targetName: nil,
        methodologyOverview: nil,
        targetEvaluate: nil,
        approachSummary: nil,
        trainingStages: [],
        milestones: [],
        createdAt: nil,
        methodologyVersion: nil,
        milestoneBasis: nil
    )
}

// MARK: - Mock Repository for AC-RDNS-05
// Uses a separate name to avoid collision with MockTrainingPlanV2Repository in Mocks/

private final class OverviewPublishingMockRepository: TrainingPlanV2Repository {
    private let overviewSubject = PassthroughSubject<PlanOverviewV2, Never>()

    var overviewDidUpdate: AnyPublisher<PlanOverviewV2, Never> {
        overviewSubject.eraseToAnyPublisher()
    }

    func fireOverviewUpdate(_ overview: PlanOverviewV2) {
        overviewSubject.send(overview)
    }

    // Minimal stubs — not called in this test
    func getPlanStatus(forceRefresh: Bool) async throws -> PlanStatusV2Response { fatalError("stub") }
    func getTargetTypes() async throws -> [TargetTypeV2] { fatalError("stub") }
    func getMethodologies(targetType: String?) async throws -> [MethodologyV2] { fatalError("stub") }
    func createOverviewForRace(targetId: String, startFromStage: String?, methodologyId: String?) async throws -> PlanOverviewV2 { fatalError("stub") }
    func createOverviewForNonRace(targetType: String, trainingWeeks: Int, availableDays: Int?, methodologyId: String?, startFromStage: String?, intendedRaceDistanceKm: Int?) async throws -> PlanOverviewV2 { fatalError("stub") }
    func getOverview() async throws -> PlanOverviewV2 { fatalError("stub") }
    func refreshOverview() async throws -> PlanOverviewV2 { fatalError("stub") }
    func updateOverview(overviewId: String, startFromStage: String?, methodologyId: String?) async throws -> PlanOverviewV2 { fatalError("stub") }
    func generateWeeklyPlan(weekOfTraining: Int, forceGenerate: Bool?, promptVersion: String?, methodology: String?) async throws -> WeeklyPlanV2 { fatalError("stub") }
    func getWeeklyPlan(weekOfTraining: Int, overviewId: String) async throws -> WeeklyPlanV2 { fatalError("stub") }
    func fetchWeeklyPlan(planId: String) async throws -> WeeklyPlanV2 { fatalError("stub") }
    func updateWeeklyPlan(planId: String, updates: UpdateWeeklyPlanRequest) async throws -> WeeklyPlanV2 { fatalError("stub") }
    func refreshWeeklyPlan(weekOfTraining: Int, overviewId: String) async throws -> WeeklyPlanV2 { fatalError("stub") }
    func deleteWeeklyPlan(planId: String) async throws { fatalError("stub") }
    func getWeeklyPreview(overviewId: String) async throws -> WeeklyPreviewV2 { fatalError("stub") }
    func applyAdjustmentItems(weekOfPlan: Int, appliedIndices: [Int]) async throws { fatalError("stub") }
    func generateWeeklySummary(weekOfPlan: Int, forceUpdate: Bool?) async throws -> WeeklySummaryV2 { fatalError("stub") }
    func getWeeklySummaries() async throws -> [WeeklySummaryItem] { fatalError("stub") }
    func getWeeklySummary(weekOfPlan: Int) async throws -> WeeklySummaryV2 { fatalError("stub") }
    func refreshWeeklySummary(weekOfPlan: Int) async throws -> WeeklySummaryV2 { fatalError("stub") }
    func deleteWeeklySummary(summaryId: String) async throws { fatalError("stub") }
    func getCachedPlanStatus() -> PlanStatusV2Response? { return nil }
    func getCachedOverview() -> PlanOverviewV2? { return nil }
    func getCachedWeeklyPlan(week: Int) -> WeeklyPlanV2? { return nil }
    func clearCache() async {}
    func clearOverviewCache() async {}
    func clearWeeklyPlanCache(weekOfTraining: Int?) async {}
    func clearWeeklySummaryCache(weekOfPlan: Int?) async {}
    func preloadData() async {}
}

// MARK: - Spy wrapping the real subscribeToOverviewUpdates mechanism for AC-RDNS-05

/// Validates that the subscription mechanism (overviewDidUpdate → forceRefresh)
/// works correctly. Uses the same Combine pattern as TrainingReadinessManager.subscribeToOverviewUpdates.
@MainActor
final class TrainingReadinessManagerTestable: ObservableObject {

    @Published var forceRefreshCallCount = 0
    private var cancellables = Set<AnyCancellable>()

    init(overviewRepository: any TrainingPlanV2Repository) {
        // Mirror the same subscription logic as TrainingReadinessManager.subscribeToOverviewUpdates
        overviewRepository.overviewDidUpdate
            .receive(on: DispatchQueue.main)
            .sink { [weak self] _ in
                Task { @MainActor [weak self] in
                    self?.forceRefreshCallCount += 1
                }
            }
            .store(in: &cancellables)
    }
}
