import XCTest
@testable import paceriz_dev

/// AC test stubs for AnnouncementListResponse resilience hardening.
/// Auto-generated by Architect — Developer fills implementation, all tests must pass.
///
/// Source ticket: aa0ac7cdace14d249c2d1802321af0a9
///   [iOS][high] 強化 AnnouncementListResponse decode 容錯
///
/// Priority (per user): crash > decode failure blocking flow > display issues
final class AnnouncementListResponseDecodingTests: XCTestCase {

    // MARK: - Helpers

    private func decode(_ json: String) throws -> AnnouncementListResponse {
        let data = Data(json.utf8)
        return try JSONDecoder().decode(AnnouncementListResponse.self, from: data)
    }

    private func validItem(id: String) -> String {
        """
        {
          "id": "\(id)",
          "title": "Title \(id)",
          "body": "Body \(id)",
          "image_url": null,
          "cta_label": null,
          "cta_url": null,
          "published_at": "2026-04-18T11:42:01.123Z",
          "expires_at": null,
          "is_seen": false
        }
        """
    }

    // MARK: - AC-ANN-RES-01: lossy decode skips bad item

    /// Given N=3 announcements where item[1] has type-mismatched field,
    /// When decoding the list,
    /// Then list contains 2 valid items, bad one skipped (not throw),
    /// And Logger.warn called with diagnostic info.
    func test_ac_ann_res_01_lossy_skips_bad_item() throws {
        let badItem = """
        {
          "id": "bad",
          "title": 12345,
          "body": "Body bad",
          "is_seen": false
        }
        """
        let json = """
        {
          "announcements": [
            \(validItem(id: "ok-1")),
            \(badItem),
            \(validItem(id: "ok-2"))
          ]
        }
        """

        let response = try decode(json)

        XCTAssertEqual(response.announcements.count, 2,
                       "Bad item should be dropped, valid ones kept")
        XCTAssertEqual(response.announcements.map(\.id), ["ok-1", "ok-2"])
    }

    // MARK: - AC-ANN-RES-02: all bad → empty list, no throw

    /// Given all items are malformed,
    /// When decoding,
    /// Then returns empty announcements (does NOT throw — message center shows empty, not crash).
    func test_ac_ann_res_02_all_bad_returns_empty() throws {
        let json = """
        {
          "announcements": [
            { "garbage": true },
            { "id": 999, "title": "wrong-type-id" }
          ]
        }
        """

        let response = try decode(json)
        XCTAssertEqual(response.announcements.count, 0)
    }

    // MARK: - AC-ANN-RES-03: missing is_seen → defaults to false (unread)

    /// Given backend omits "is_seen" field on every item,
    /// When decoding,
    /// Then items decode successfully and Mapper treats them as unread (false).
    /// Rationale: showing popup is safer than hiding it (priority 3: avoid blank).
    func test_ac_ann_res_03_missing_is_seen_defaults_false() throws {
        let json = """
        {
          "announcements": [
            {
              "id": "missing-seen",
              "title": "Title",
              "body": "Body",
              "published_at": "2026-04-18T11:42:01Z"
            }
          ]
        }
        """

        let response = try decode(json)
        XCTAssertEqual(response.announcements.count, 1)
        let dto = response.announcements[0]
        let domain = AnnouncementMapper.toDomain(dto)
        XCTAssertNotNil(domain)
        XCTAssertEqual(domain?.isSeen, false,
                       "Missing is_seen must default to unread (false)")
    }

    // MARK: - AC-ANN-RES-04: ISO8601 with fractional seconds

    func test_ac_ann_res_04_iso8601_fractional() throws {
        let json = """
        {
          "announcements": [{
            "id": "frac",
            "title": "T",
            "body": "B",
            "published_at": "2026-04-18T11:42:01.123Z",
            "is_seen": false
          }]
        }
        """
        let response = try decode(json)
        let domain = AnnouncementMapper.toDomain(response.announcements[0])
        XCTAssertNotNil(domain, "Fractional seconds ISO8601 must parse")
    }

    // MARK: - AC-ANN-RES-05: ISO8601 without fractional seconds

    func test_ac_ann_res_05_iso8601_no_fractional() throws {
        let json = """
        {
          "announcements": [{
            "id": "no-frac",
            "title": "T",
            "body": "B",
            "published_at": "2026-04-18T11:42:01Z",
            "is_seen": false
          }]
        }
        """
        let response = try decode(json)
        let domain = AnnouncementMapper.toDomain(response.announcements[0])
        XCTAssertNotNil(domain, "Plain ISO8601 (no fractional) must parse")
    }

    // MARK: - AC-ANN-RES-06: empty array

    func test_ac_ann_res_06_empty_array() throws {
        let json = #"{ "announcements": [] }"#
        let response = try decode(json)
        XCTAssertEqual(response.announcements.count, 0)
    }
}
